# This pipeline will:
# - Provision an Azure VM.
# 
# 
#
# The following variables need to be provided to the pipeline:
#
# - subscriptionId           : Subscription Id.
# - snapshotNameOs           : Name for snapshot containing the OS.
# - snapshotNameData         : Name for snapshot containing the Data.
# - dest-container           : Location for Managed Disks.
# - dest-blob                : Name for Managed Disk containing the OS.
# - storage-account          : Name for Managed Disk containing the data.
#
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'MyAzureServiceConnection'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  subscriptionId: "0ac447d7-fbc3-4d3d-84d4-37bb9a71e089"
  source-container: "snapshot-rg"
  source-blob: "swedencentral"
  osDiskName: "easec-vm_OsDisk_1_man"
  dataDiskName: "easec-vm_DataDisk_1_man"
  diskSizeOs: 128
  diskSizeData: 40
  vhdUriOS: "https://snapshottestsa.blob.core.windows.net/snapshot/easec-vm_OsDisk_1_snap.vhd"
  vhdUriData: "https://snapshottestsa.blob.core.windows.net/snapshot/easec-vm_DataDisk_1_snap.vhd"
  storageType: "Premium_LRS"
  osType: "windows"
  hyperVGeneration: "v2"
  vmSize: "Standard_DS1_v2"
  virtualMachineName: "easec-vm"

stages:
- stage: Provision
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'MyAzureServiceConnection'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az storage blob copy start --source-container "$(source-container)" --source-blob "$(source-blob)" --destination-container "$(dest-container)" --destination-blob "$(dest-blob)" --account-name "$(storage-account)" --tier hot --rehydrate-priority standard --auth-mode login
