# This pipeline will:
# - Provision an Azure VM.
# 
# 
#
# The following variables need to be provided to the pipeline:
#
# - subscriptionId           : Subscription Id.
# - storage-account          : Name for Storage account.
# - source-container         : Name for source container.
# - source-blob-os           : Name for source blob containing OS.
# - source-blob-data         : Name for source blob containing data.
# - dest-container           : Name for destination container.
# - dest-blob-os             : Name for destination blob containing OS.
# - dest-blob-data           : Name for destination blob containing data.
# - account-key              : Provided through variables (Azure DevOps) - contains value that should be a secret
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'MyAzureServiceConnection'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  subscriptionId: "0ac447d7-fbc3-4d3d-84d4-37bb9a71e089"
  source-container: "iscala-archive"
  source-blob-os: "easec-vm_OsDisk_1_snap.vhd"
  source-blob-data: "easec-vm_DataDisk_1_snap.vhd"
  dest-container: "snapshot"
  dest-blob-os: "easec-vm_OsDisk_1_snap.vhd"
  dest-blob-data: "easec-vm_DataDisk_1_snap.vhd"
  storage-account: snapshottestsa

stages:
- stage: Provision
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'MyAzureServiceConnection'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az storage blob copy start --source-container "$(source-container)" --source-blob "$(source-blob-os)" --destination-container "$(dest-container)" --destination-blob "$(dest-blob-os)" --account-name "$(storage-account)" --account-key "$(account-key)" --tier hot --rehydrate-priority standard
          az storage blob copy start --source-container "$(source-container)" --source-blob "$(source-blob-data)" --destination-container "$(dest-container)" --destination-blob "$(dest-blob-data)" --account-name "$(storage-account)" --account-key "$(account-key)" --tier hot --rehydrate-priority standard
