# This pipeline will:
# - Provision an Azure VM.
# 
# 
#
# The following variables need to be provided to the pipeline:
#
# - subscriptionId           : Subscription Id.
# - source-container         : Name for source container.
# - source-blob              : Name for source blob containing OS.
# - dest-container           : Name for destination container.
# - dest-blob                : Name for destination blob containing OS.
# - storage-account          : Name for Storage account.
#
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'MyAzureServiceConnection'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  subscriptionId: "0ac447d7-fbc3-4d3d-84d4-37bb9a71e089"
  source-container: "iscala-archive"
  source-blob: "easec-vm_DataDisk_1_snap.vhd"
  dest-container: "snapshot"
  dest-blob: "easec-vm_ODataDisk_1_snap.vhd"
  storage-account: snapshottestsa

stages:
- stage: Provision
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'MyAzureServiceConnection'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az storage blob copy start --source-container "$(source-container)" --source-blob "$(source-blob)" --destination-container "$(dest-container)" --destination-blob "$(dest-blob)" --account-name "$(storage-account)" --tier hot --rehydrate-priority standard
